import Link from 'next/link';

export default function Home() {
  return <main className="page"><div className="shell"><nav className="nav"><Link href="/" className="brand"><div className="mark">12</div><span>THE 12TH</span></Link><div className="navRight"><div className="live"><i className="dot"/> REAL LIVE</div><Link href="/leaderboard">LEADERBOARD</Link><Link href="/profile">MY IQ</Link></div></nav>
    <section className="hero"><div><div className="eyebrow">REAL-TIME FOOTBALL INTELLIGENCE</div><h1>READ THE GAME.<br/><span style={{color:'var(--green)'}}>MAKE THE CALL.</span></h1><p className="sub">Gerçek canlı maçları takip et. Maç sonucu, exact skor, ilk gol, kart, toplam gol, karşılıklı gol, sıradaki olay ve taktik kararlarında tahmin yap. Sonra gerçek oyunla kendini ölç.</p><Link href="/matches" className="submit" style={{display:'inline-block',width:'auto',padding:'13px 20px'}}>GERÇEK CANLI MAÇLARA GİT →</Link></div><div className="statStrip"><div className="mini"><b>LIVE</b><span>REAL MATCH DATA</span></div><div className="mini"><b>8</b><span>PREDICTION TYPES</span></div><div className="mini"><b>IQ</b><span>NO BETTING</span></div></div></section>
    <section className="grid"><div className="card"><span className="label">THE 12TH SYSTEM</span><h2>Maçın sadece skorunu değil, oyunun tamamını oku.</h2><p className="sub">Tahminlerin gerçek maç olaylarıyla karşılaştırılır. Ne kadar isabetli, zamanında ve tutarlı karar verdiğin Football IQ skoruna yansır.</p></div><aside className="side"><div className="card iq"><span className="label">TAHMİN ALANLARI</span><div className="rows"><div className="row"><span>Maç sonucu</span><b>3</b></div><div className="row"><span>Exact skor</span><b>12</b></div><div className="row"><span>İlk gol</span><b>3</b></div><div className="row"><span>Kart / gol / olay</span><b>10+</b></div></div></div></aside></section>
    <footer className="footer"><span>THE 12TH © 2026 — FOOTBALL INTELLIGENCE</span><span>NO BETTING. JUST THE GAME.</span></footer>
  </div></main>;
}
